package vista;

import java.awt.BorderLayout;

import javax.swing.JPanel;

import modelo.AlumnoSubject;
import modelo.ListaTalleresSubject;
import modelo.Subject;
import modelo.TallerSubject;
import modelo.TicketSubject;
import vista.paneles.PanelDetallesTaller;
import vista.paneles.PanelTicket;
import vista.paneles.PanelValidacionAlumno;

/**
 * PantallaInscripcion.java
 * 
 * Frame que representa la pantalla principal del caso de uso de inscribirse
 * a taller de Semana ISW, es en una sola pantalla y esta se va actualizando
 * cada que cambia algo del modelo. 
 * 
 * @author Pedro Luna Esquer - 252687
 */
public class PantallaInscripcion extends javax.swing.JFrame {
    
    /**
     * Instancia de la pantalla del caso de uso (Singleton)
     */
    private static PantallaInscripcion instance;

    /**
     * Creates new form PantallaInscripcion
     */
    private PantallaInscripcion() {
        initComponents();
    }

    /**
     * Metodo para obtener la instancia única de la pantalla del caso de uso.
     */
    public static PantallaInscripcion getInstance(){
        if(instance==null){
            instance = new PantallaInscripcion();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelContenedorDetalles = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelTalleres = new vista.paneles.PanelTalleres();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("Inscripción a Taller de Semana de ISW");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(67, 56, 202), 1, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(67, 56, 202));
        jLabel2.setText("Detalles y Proceso");

        panelContenedorDetalles.setBackground(new java.awt.Color(255, 255, 255));
        panelContenedorDetalles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione un Taller en el panel izquierdo para comenzar");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bienvenido a la Selección de Talleres");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContenedorDetalles.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -9, 501, 300));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenedorDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelContenedorDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTalleres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo que se llama cuando cambia algo del modelo
     * @param subject Recibe un subject que fue la clase que cambio
     */
    public void actualizarVista(Subject subject){
        actualizarPanelesTalleres(subject);
        mostrarDetallesTaller(subject);
        mostrarDatosAlumno(subject);
        mostrarTicket(subject);
    }

    /**
     * Metodo para actualizar el panel que contiene a los talleres si el sujeto es la lista de talleres
     * @param subject Sujeto observado.
     */
    private void actualizarPanelesTalleres(Subject subject){
        if(subject instanceof ListaTalleresSubject){
            ListaTalleresSubject listaTalleres = (ListaTalleresSubject) subject;
            panelTalleres.actualizarTalleres(listaTalleres);
            repaint();
            revalidate();
        }
    }

    /**
     * Metodo para mostrar los detalles del taller si el sujeto obtenido es un taller seleccionado
     * @param subject Sujeto observado
     */
    private void mostrarDetallesTaller(Subject subject){
        if(subject instanceof TallerSubject){
            TallerSubject taller = (TallerSubject) subject;
            PanelDetallesTaller panelDetalles = new PanelDetallesTaller(taller);
            cambiarContenedorDetalles(panelDetalles);
        }
    }

    /**
     * Metodo para mostrar los datos de los alumnos si el sujeto es un alumno
     * @param subject Sujeto observado
     */
    private void mostrarDatosAlumno(Subject subject) {
        if (subject instanceof AlumnoSubject){
            AlumnoSubject alumno = (AlumnoSubject) subject;
            PanelValidacionAlumno panelFormularioID = new PanelValidacionAlumno();
            panelFormularioID.mostrarDatosAlumno(alumno);
            cambiarContenedorDetalles(panelFormularioID);
        }
    }

    /**
     * Metodo para mostrar el formulario ID cuando se da clic en inscribir
     */
    public void mostrarFormularioID(){
        PanelValidacionAlumno panelFormularioID = new PanelValidacionAlumno();
        cambiarContenedorDetalles(panelFormularioID);
    }

    /**
     * Metodo para mostrar el ticket de inscripcion si el sujeto es un ticket
     * @param subject Sujeto observado
     */
    private void mostrarTicket(Subject subject){
        if(subject instanceof TicketSubject){
            TicketSubject ticket = (TicketSubject) subject;
            PanelTicket panelTicket = new PanelTicket(ticket);
            cambiarContenedorDetalles(panelTicket);
        }
    }
    
    /**
     * Metodo para cambiar el contenido del panel que contiene el proceso de la inscripcion
     * @param panel Nuevo panel a mostrar dentro del proceso.
     */
    private void cambiarContenedorDetalles(JPanel panel){
        panelContenedorDetalles.removeAll();
        panelContenedorDetalles.setLayout(new BorderLayout());
        panelContenedorDetalles.add(panel, BorderLayout.CENTER);
        panelContenedorDetalles.repaint();
        panelContenedorDetalles.revalidate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelContenedorDetalles;
    private vista.paneles.PanelTalleres panelTalleres;
    // End of variables declaration//GEN-END:variables
}
