/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.paneles;

import modelo.AlumnoSubject;
import modelo.TallerSubject;
import modelo.TicketSubject;

/**
 * PanelTicket.java
 * 
 * Panel que muestra la inforamación de la inscripción a un taller de un alumno
 * @author pedro
 */
public class PanelTicket extends javax.swing.JPanel {

    /**
     * Creates new form PanelTicket
     */
    public PanelTicket(TicketSubject ticket) {
        initComponents();
        cargarTicket(ticket);
    }

    /**
     * Carga la info de la inscripcion en las etiquetas visuales
     * @param ticket Ticket a mostrar en el panel
     */
    private void cargarTicket(TicketSubject ticket){
        TallerSubject taller = ticket.getTaller();
        AlumnoSubject alumno = ticket.getAlumno();
        lblNombreTaller.setText(taller.getNombre());
        lblFolio.setText(ticket.getFolio());
        lblAlumno.setText(alumno.getNombre());
        lblInstructor.setText(taller.getInstructor());
        lblPrograma.setText(alumno.getPrograma());
        lblHorario.setText(taller.getFechaYHora());
        lblFechaRegistro.setText(ticket.getFechaRegistro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlumno1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreTaller = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFolio = new javax.swing.JLabel();
        lblFolio1 = new javax.swing.JLabel();
        lblFolio2 = new javax.swing.JLabel();
        lblFolio3 = new javax.swing.JLabel();
        lblFolio4 = new javax.swing.JLabel();
        lblFechaRegistro = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        lblInstructor = new javax.swing.JLabel();
        lblPrograma = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();

        lblAlumno1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAlumno1.setForeground(new java.awt.Color(255, 255, 255));
        lblAlumno1.setText("Alumno:");

        jPanel1.setBackground(new java.awt.Color(45, 55, 70));
        jPanel1.setMaximumSize(new java.awt.Dimension(486, 287));
        jPanel1.setMinimumSize(new java.awt.Dimension(486, 287));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 204, 21));
        jLabel1.setText("TICKET DE INSCRIPCIÓN");

        lblNombreTaller.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreTaller.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreTaller.setText("Nombre Taller");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Folio de Registro: ");

        lblFolio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblFolio.setForeground(new java.awt.Color(255, 255, 255));
        lblFolio.setText("Folio de Registro: ");

        lblFolio1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFolio1.setForeground(new java.awt.Color(255, 255, 255));
        lblFolio1.setText("Alumno:");

        lblFolio2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFolio2.setForeground(new java.awt.Color(255, 255, 255));
        lblFolio2.setText("Instructor:");

        lblFolio3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFolio3.setForeground(new java.awt.Color(255, 255, 255));
        lblFolio3.setText("Programa:");

        lblFolio4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFolio4.setForeground(new java.awt.Color(255, 255, 255));
        lblFolio4.setText("Horario:");

        lblFechaRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaRegistro.setText("Registrado el");

        lblAlumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblAlumno.setText("Alumno:");

        lblInstructor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInstructor.setForeground(new java.awt.Color(255, 255, 255));
        lblInstructor.setText("lblInstructor");

        lblPrograma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrograma.setForeground(new java.awt.Color(255, 255, 255));
        lblPrograma.setText("Programa:");

        lblHorario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHorario.setForeground(new java.awt.Color(255, 255, 255));
        lblHorario.setText("Horario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(lblFolio))
                    .addComponent(lblFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFolio2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFolio1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFolio3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFolio4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblNombreTaller)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblFolio))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFolio1)
                    .addComponent(lblAlumno)
                    .addComponent(lblFolio3)
                    .addComponent(lblPrograma))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFolio2)
                    .addComponent(lblInstructor)
                    .addComponent(lblFolio4)
                    .addComponent(lblHorario))
                .addGap(18, 18, 18)
                .addComponent(lblFechaRegistro))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblAlumno1;
    private javax.swing.JLabel lblFechaRegistro;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblFolio1;
    private javax.swing.JLabel lblFolio2;
    private javax.swing.JLabel lblFolio3;
    private javax.swing.JLabel lblFolio4;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblInstructor;
    private javax.swing.JLabel lblNombreTaller;
    private javax.swing.JLabel lblPrograma;
    // End of variables declaration//GEN-END:variables
}
