package vista.paneles;

import java.awt.Color;
import java.util.LinkedList;
import java.util.List;

import javax.swing.Box;
import javax.swing.border.LineBorder;

import modelo.ListaTalleresSubject;
import modelo.TallerSubject;

/**
 *
 * @author pedro
 */
public class PanelTalleres extends javax.swing.JPanel {

    private static List<PanelTaller> panelesTalleres;

    /**
     * Creates new form PanelTalleres
     */
    public PanelTalleres() {
        panelesTalleres = new LinkedList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelContenedorTalleres = new javax.swing.JPanel();

        setBackground(new java.awt.Color(249, 250, 251));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(194, 194, 194), 1, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Talleres Disponibles");

        jScrollPane1.setBackground(new java.awt.Color(249, 250, 251));
        jScrollPane1.setBorder(null);

        panelContenedorTalleres.setBackground(new java.awt.Color(249, 250, 251));
        panelContenedorTalleres.setLayout(new javax.swing.BoxLayout(panelContenedorTalleres, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelContenedorTalleres);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarTalleres(ListaTalleresSubject listaTalleres){
        List<TallerSubject> talleres = listaTalleres.getListaTalleres();
        panelContenedorTalleres.removeAll();
        for(TallerSubject taller : talleres){
            PanelTaller panelTaller = new PanelTaller(taller);
            panelesTalleres.add(panelTaller);
            panelContenedorTalleres.add(panelTaller);
            panelContenedorTalleres.add(Box.createVerticalStrut(12));
        }
        repaint();
        revalidate();
    }

    public static void despintarPaneles(){
        for(PanelTaller panel : panelesTalleres){
            panel.setBackground(Color.WHITE);
            panel.setBorder(new LineBorder(new Color(194,194,194), 1, true));
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelContenedorTalleres;
    // End of variables declaration//GEN-END:variables
}
