package vista.paneles;

import java.awt.BorderLayout;

import javax.swing.JOptionPane;

import control.ControlInscribirTaller;
import exceptions.AlumnoNoEncontradoException;
import modelo.AlumnoSubject;

/**
 *
 * @author pedro
 */
public class PanelValidacionAlumno extends javax.swing.JPanel {

    /**
     * Creates new form PanelValidacionAlumno
     */
    public PanelValidacionAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNombreTaller = new javax.swing.JLabel();
        lblInstructor = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();
        txtIDAlumno = new javax.swing.JTextField();
        btnInscribirse = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(486, 287));
        jPanel1.setMinimumSize(new java.awt.Dimension(486, 287));

        lblNombreTaller.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreTaller.setText("Validación de Identidad");

        lblInstructor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblInstructor.setText("Para continuar con la inscripción por favor ingresa tu ID de Alumno");

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        txtIDAlumno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtIDAlumno.setForeground(new java.awt.Color(167, 166, 166));
        txtIDAlumno.setText("Ingresa tu ID (ej: 123456)");
        txtIDAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDAlumnoMouseClicked(evt);
            }
        });

        btnInscribirse.setBackground(new java.awt.Color(22, 175, 101));
        btnInscribirse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInscribirse.setForeground(new java.awt.Color(255, 255, 255));
        btnInscribirse.setText("Validar ID");
        btnInscribirse.setFocusPainted(false);
        btnInscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
                panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtIDAlumno)
                        .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnInscribirse, javax.swing.GroupLayout.PREFERRED_SIZE, 198,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(259, Short.MAX_VALUE)));
        panelContenedorLayout.setVerticalGroup(
                panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtIDAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnInscribirse, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(49, Short.MAX_VALUE)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(lblNombreTaller, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, 471,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblNombreTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDAlumnoMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_txtIDAlumnoMouseClicked
        txtIDAlumno.setText("");
    }// GEN-LAST:event_txtIDAlumnoMouseClicked

    private void btnInscribirseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInscribirseActionPerformed
        String id = txtIDAlumno.getText();
        if (!id.matches("\\d{6}")) {
            JOptionPane.showMessageDialog(null, "Error: Formato Inválido, asegurese de ingresar un ID de 6 digitos",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ControlInscribirTaller control = new ControlInscribirTaller();
        try{
            control.validarID(id);
        } catch (AlumnoNoEncontradoException e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnInscribirseActionPerformed

    public void mostrarDatosAlumno(AlumnoSubject alumno) {
        PanelDatosAlumno panelAlumno = new PanelDatosAlumno(alumno);
        panelContenedor.removeAll();
        panelContenedor.setLayout(new BorderLayout());
        panelContenedor.add(panelAlumno, BorderLayout.CENTER);
        panelContenedor.repaint();
        panelContenedor.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribirse;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInstructor;
    private javax.swing.JLabel lblNombreTaller;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JTextField txtIDAlumno;
    // End of variables declaration//GEN-END:variables
}
