package vista.paneles;

import modelo.TallerSubject;
import java.awt.Color;

import javax.swing.border.LineBorder;

import control.ControlInscribirTaller;
/**
 *
 * @author pedro
 */
public class PanelTaller extends javax.swing.JPanel {

    /**
     * Creates new form PanelTaller
     */
    public PanelTaller(TallerSubject taller) {
        initComponents();
        cargarTaller(taller);
    }

    private void cargarTaller(TallerSubject taller){
        this.lblNombreTaller.setText(taller.getNombre());
        this.lblInstructor.setText(taller.getInstructor());
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreTaller = new javax.swing.JLabel();
        lblInstructor = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(194, 194, 194), 1, true));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblNombreTaller.setText("Nombre Taller");

        lblInstructor.setText("Instructor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreTaller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNombreTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        mostrarDetallesTaller();
        PanelTalleres.despintarPaneles();
        cambiarColor();
    }//GEN-LAST:event_formMouseClicked

    private void mostrarDetallesTaller(){
        ControlInscribirTaller control = new ControlInscribirTaller();
        control.seleccionarTaller(lblNombreTaller.getText());
    }

    private void cambiarColor(){
        this.setBackground(new Color(199,210,254));
        this.setBorder(new LineBorder(Color.BLACK, 1, true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblInstructor;
    private javax.swing.JLabel lblNombreTaller;
    // End of variables declaration//GEN-END:variables
}
